// Copyright The kube-workspaces Authors.
// SPDX-License-Identifier: Apache-2.0

package keysym

import (
	"math/bits"
	"strings"
)

// Modifiers is a bitmask of the modifier and lock state reported by the
// windowing layer.
//
// It is a compact summary, not a substitute for the [Key] values: it does not
// distinguish left from right. Use it for decisions ("is Control held?") and
// use [Key] values when actually generating events, since the guest cares
// which physical modifier arrived.
type Modifiers uint16

// The defined modifier bits.
const (
	ModShift Modifiers = 1 << iota
	ModControl
	ModAlt
	ModSuper
	// ModAltGr is the third-level shift (ISO_Level3_Shift). It is tracked
	// separately from Alt because on most non-US layouts it is a distinct key
	// that produces characters rather than a command modifier.
	ModAltGr
	ModCapsLock
	ModNumLock

	// ModNone is the empty set.
	ModNone Modifiers = 0
)

// modNames lists each bit with its stable lowercase name, in the order
// [Modifiers.String] emits them.
var modNames = []struct {
	bit  Modifiers
	name string
}{
	{ModShift, "shift"},
	{ModControl, "control"},
	{ModAlt, "alt"},
	{ModSuper, "super"},
	{ModAltGr, "altgr"},
	{ModCapsLock, "capslock"},
	{ModNumLock, "numlock"},
}

// modKeys maps each bit to the key it is generated by. The left-hand key is
// chosen because that is what an unqualified modifier means; see keyAliases.
var modKeys = []struct {
	bit Modifiers
	key Key
}{
	{ModShift, KeyShiftL},
	{ModControl, KeyControlL},
	{ModAlt, KeyAltL},
	{ModSuper, KeySuperL},
	{ModAltGr, KeyAltGr},
	{ModCapsLock, KeyCapsLock},
	{ModNumLock, KeyNumLock},
}

// Has reports whether every bit in m is set in mods. Has(ModNone) is true.
func (m Modifiers) Has(mods Modifiers) bool { return m&mods == mods }

// HasAny reports whether any bit in mods is set in m.
func (m Modifiers) HasAny(mods Modifiers) bool { return m&mods != 0 }

// With returns m with mods set.
func (m Modifiers) With(mods Modifiers) Modifiers { return m | mods }

// Without returns m with mods cleared.
func (m Modifiers) Without(mods Modifiers) Modifiers { return m &^ mods }

// Count returns the number of bits set.
func (m Modifiers) Count() int { return bits.OnesCount16(uint16(m)) }

// String renders the set as "shift|control", or "none" when empty. The order
// is fixed so the output is stable and comparable in tests.
func (m Modifiers) String() string {
	if m == ModNone {
		return "none"
	}
	parts := make([]string, 0, len(modNames))
	for _, n := range modNames {
		if m&n.bit != 0 {
			parts = append(parts, n.name)
		}
	}
	if len(parts) == 0 {
		return "none"
	}
	return strings.Join(parts, "|")
}

// Keys returns the modifier keys corresponding to the bits in m, in the fixed
// order of [Modifiers.String]. Lock bits yield their lock keys, which callers
// synthesising a chord usually want to filter out: toggling Caps Lock is not
// the same as holding a modifier.
func (m Modifiers) Keys() []Key {
	keys := make([]Key, 0, m.Count())
	for _, mk := range modKeys {
		if m&mk.bit != 0 {
			keys = append(keys, mk.key)
		}
	}
	return keys
}

// Keysyms returns the keysyms for [Modifiers.Keys].
func (m Modifiers) Keysyms() []Keysym {
	keys := m.Keys()
	syms := make([]Keysym, 0, len(keys))
	for _, k := range keys {
		if sym := k.Keysym(); sym != NoSymbol {
			syms = append(syms, sym)
		}
	}
	return syms
}

// ModifierOf returns the [Modifiers] bit that k contributes, and reports
// whether k is a modifier at all. Left and right variants collapse onto the
// same bit, which is the point of the bitmask.
func ModifierOf(k Key) (Modifiers, bool) {
	switch k {
	case KeyShiftL, KeyShiftR, KeyShiftLock:
		return ModShift, true
	case KeyControlL, KeyControlR:
		return ModControl, true
	case KeyAltL, KeyAltR, KeyMetaL, KeyMetaR:
		// Meta collapses onto Alt: on PC keyboards the Meta keysyms are what
		// some layouts emit for the physical Alt keys.
		return ModAlt, true
	case KeySuperL, KeySuperR, KeyHyperL, KeyHyperR:
		return ModSuper, true
	case KeyAltGr, KeyModeSwitch:
		return ModAltGr, true
	case KeyCapsLock:
		return ModCapsLock, true
	case KeyNumLock:
		return ModNumLock, true
	default:
		return ModNone, false
	}
}

// ModifiersOf returns the combined bitmask for a set of modifier keys,
// ignoring any key that is not a modifier.
func ModifiersOf(keys ...Key) Modifiers {
	var m Modifiers
	for _, k := range keys {
		if bit, ok := ModifierOf(k); ok {
			m |= bit
		}
	}
	return m
}

// Tracker records which modifier keysyms this client has told the guest are
// held down.
//
// It exists because RFB carries no modifier state. The guest's idea of which
// modifiers are held is built purely from the KeyEvent stream, so if the
// client sends a press and never the matching release, the modifier stays
// down in the guest forever: every subsequent keystroke arrives shifted, or
// as a Ctrl shortcut, and the session becomes unusable.
//
// The usual way that happens is focus loss mid-chord. The user presses Alt-Tab
// and the host window manager steals the release, or the window is minimised
// while Ctrl is held, and the client never observes the key-up. Every usable
// VDI client therefore releases all held modifiers when its window loses focus
// or the session is suspended; [Tracker.ReleaseAll] produces exactly those
// events.
//
// A Tracker models what the guest believes, not what the user is physically
// holding. The two can differ: if the user holds Ctrl while the client injects
// Ctrl-Alt-Del, the chord's trailing Ctrl-up really does tell the guest that
// Ctrl is released, so the Tracker stops considering it held even though the
// physical key is still down. That is deliberate — tracking the physical key
// instead would make [Tracker.ReleaseAll] emit a second release for a key the
// guest already considers up.
//
// A Tracker is not safe for concurrent use. Feed it from the same goroutine
// that owns the input event loop.
type Tracker struct {
	// held is ordered by press time so that ReleaseAll can unwind it as a
	// stack, matching the ordering rule in Chord.Sequence.
	held []Keysym
}

// Track records a key event. Non-modifier keysyms and [NoSymbol] are ignored,
// so the input loop can pass every event through without filtering first.
//
// It reports whether the tracked state changed.
func (t *Tracker) Track(sym Keysym, down bool) bool {
	if sym == NoSymbol || !sym.IsModifier() {
		return false
	}
	if down {
		return t.press(sym)
	}
	return t.release(sym)
}

// TrackKey is [Tracker.Track] for a [Key].
func (t *Tracker) TrackKey(k Key, down bool) bool { return t.Track(k.Keysym(), down) }

// TrackAction is [Tracker.Track] for a [KeyAction], so the actions produced by
// [Chord.Sequence] can be fed straight back in as they are sent.
func (t *Tracker) TrackAction(a KeyAction) bool { return t.Track(a.Sym, a.Down) }

func (t *Tracker) press(sym Keysym) bool {
	if t.IsHeld(sym) {
		// Auto-repeat resends the press; it must not push a duplicate, or
		// ReleaseAll would emit two releases for one key.
		return false
	}
	t.held = append(t.held, sym)
	return true
}

func (t *Tracker) release(sym Keysym) bool {
	for i, h := range t.held {
		if h == sym {
			t.held = append(t.held[:i], t.held[i+1:]...)
			return true
		}
	}
	return false
}

// IsHeld reports whether sym is currently held.
func (t *Tracker) IsHeld(sym Keysym) bool {
	for _, h := range t.held {
		if h == sym {
			return true
		}
	}
	return false
}

// Held returns the held modifier keysyms in press order. It returns a fresh
// slice on each call.
func (t *Tracker) Held() []Keysym {
	held := make([]Keysym, len(t.held))
	copy(held, t.held)
	return held
}

// Len returns the number of modifiers currently held.
func (t *Tracker) Len() int { return len(t.held) }

// Modifiers returns the tracked state as a bitmask.
func (t *Tracker) Modifiers() Modifiers {
	var m Modifiers
	for _, sym := range t.held {
		if k, ok := keyForSym[sym]; ok {
			if bit, isMod := ModifierOf(k); isMod {
				m |= bit
			}
		}
	}
	return m
}

// ReleaseAll returns the key-up events needed to clear every held modifier in
// the guest, and forgets them.
//
// Releases are emitted in reverse press order, unwinding the modifiers as a
// stack for the same reason [Chord.Sequence] does: it is the order a real
// keyboard produces, and it never leaves a lone Alt held, which on Windows
// guests would pop the menu bar.
//
// Send the result whenever the client can no longer observe key releases —
// window focus loss, session suspend, or before disconnecting. Calling it when
// nothing is held returns nil and is harmless, so callers need not check
// first.
func (t *Tracker) ReleaseAll() []KeyAction {
	if len(t.held) == 0 {
		return nil
	}
	actions := make([]KeyAction, 0, len(t.held))
	for i := len(t.held) - 1; i >= 0; i-- {
		actions = append(actions, KeyAction{Sym: t.held[i], Down: false})
	}
	t.held = t.held[:0]
	return actions
}

// Reset forgets all tracked state without producing any events. Use it only
// when the connection itself is gone, so the guest's state no longer matters;
// otherwise use [Tracker.ReleaseAll].
func (t *Tracker) Reset() { t.held = t.held[:0] }
